# Generated by Django 3.2 on 2021-12-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_reservationinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='listings.listing'),
        ),
    ]
