# Generated by Django 3.2 on 2021-12-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20211206_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationinfo',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationinfo',
            name='checkout',
            field=models.DateField(),
        ),
    ]
