# Generated by Django 3.2 on 2021-12-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20211206_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationinfo',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservationinfo',
            name='checkout',
            field=models.DateTimeField(),
        ),
    ]
